#!/usr/bin/env bash
set -euo pipefail

# Skip in CI environments
if [[ "${CI:-}" == "true" ]] || [[ "${GITHUB_ACTIONS:-}" == "true" ]] || [[ "${VERCEL:-}" == "1" ]]; then
  echo "[supabase-dev] CI detected, skipping local Supabase setup"
  exit 0
fi

# Detect Supabase CLI
SUPABASE_CMD=""
if command -v supabase &> /dev/null; then
  SUPABASE_CMD="supabase"
elif command -v npx &> /dev/null; then
  SUPABASE_CMD="npx supabase"
else
  echo "[supabase-dev] Supabase CLI not found. Install with: brew install supabase/tap/supabase"
  echo "[supabase-dev] Falling back to local-only mode (no Supabase backend)"
  exit 0
fi

# Check Docker
if ! docker info &> /dev/null 2>&1; then
  echo "[supabase-dev] Docker is not running. Start Docker Desktop first."
  echo "[supabase-dev] Falling back to local-only mode (no Supabase backend)"
  exit 0
fi

echo "[supabase-dev] Starting Supabase local development stack..."

# Start Supabase (idempotent)
$SUPABASE_CMD start 2>/dev/null || true

# Parse status
STATUS_JSON=$($SUPABASE_CMD status --output json 2>/dev/null || echo '{}')

API_URL=$(echo "$STATUS_JSON" | grep -o '"API URL": *"[^"]*"' | head -1 | sed 's/.*: *"//;s/"//' || echo "")
ANON_KEY=$(echo "$STATUS_JSON" | grep -o '"anon key": *"[^"]*"' | head -1 | sed 's/.*: *"//;s/"//' || echo "")

if [[ -z "$API_URL" || -z "$ANON_KEY" ]]; then
  echo "[supabase-dev] Could not parse Supabase status. Check 'supabase status' manually."
  exit 0
fi

# Generate .env.local for the web app
ENV_FILE="apps/web/.env.local"
cat > "$ENV_FILE" << EOF
# Auto-generated by scripts/supabase-dev.sh
VITE_SUPABASE_URL=$API_URL
VITE_SUPABASE_ANON_KEY=$ANON_KEY
EOF

echo "[supabase-dev] Generated $ENV_FILE"
echo "[supabase-dev] Supabase API: $API_URL"
echo "[supabase-dev] Supabase ready!"
